"""
Gatherer Agent — Stage 2 of the Research Workflow.

═══════════════════════════════════════════════════════════════════
PURPOSE:
    Executes search queries generated by the Planner across multiple
    source types. Uses LLM-driven tool selection to decide which
    retrieval tools to invoke for each query based on context.

LLM-DRIVEN TOOL SELECTION:
    Unlike a static dispatch table, this agent uses the LLM to:
    1. Analyze each query's intent, topic, and keywords
    2. Decide which tool(s) to invoke (web search, document search,
       data parse, or multiple)
    3. Optionally rephrase queries for each tool's strengths
    4. Assess retrieval quality and decide whether to retry with
       an alternative tool

    This demonstrates "agent uses tools, not just text generation"
    — the LLM actively reasons about tool selection at each step.

TRIGGER:
    Activated after the Planner completes successfully.

ERROR HANDLING:
    - Individual source failures are logged but don't halt the pipeline.
    - Each RawSourceData includes a retrieval_status field.
    - If ALL sources fail, the router retries or triggers error_handler.
    - Guardrails: output schema validation on LLM tool-selection output.
═══════════════════════════════════════════════════════════════════
"""

from __future__ import annotations
import json
import uuid
import logging
from datetime import datetime
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage

from config import config
from models.source import RawSourceData, SourceType, SearchQuery
from tools.web_search import search_web_tavily
from tools.document_loader import load_documents
from tools.data_parser import parse_provided_data
from guardrails import enforce_json_schema, detect_refusal

logger = logging.getLogger(__name__)


# ── LLM-Driven Tool Selection Prompt ──────────────────────────────
TOOL_SELECTOR_PROMPT = """You are a Tool Selection Agent. Given a research query, decide which retrieval tool(s) to use and how to optimize the query for each.

Available tools:
1. "web_search" — Search the live web for current news, articles, reports, statistics. Best for: recent events, market data, company news, trends, comparisons.
2. "document_search" — Search an internal document store (PDFs, reports, whitepapers). Best for: academic papers, internal reports, technical documentation.
3. "data_parse" — Parse structured/provided datasets (CSV, JSON, databases). Best for: numerical analysis, data tables, provided datasets.

Return JSON:
{
    "tool_decisions": [
        {
            "tool_name": "web_search",
            "optimized_query": "Refined query optimized for this tool",
            "reasoning": "Why this tool is best for this query",
            "priority": 1,
            "expected_value": "high"
        }
    ]
}

Rules:
- Choose 1-3 tools per query based on what would yield the BEST results
- Always include at least one tool
- Rephrase queries to match each tool's strengths (e.g., keyword-heavy for web, semantic for documents)
- "expected_value" is "high", "medium", or "low" — skip "low" value tools
- ONLY output valid JSON. No markdown, no explanation text.
"""


# ── Tool Registry ──────────────────────────────────────────────────
# Maps tool names to executable functions. The LLM chooses from these
# by name — it never calls them directly, maintaining the safety boundary.

def _execute_web_search(query: str) -> list[RawSourceData]:
    """Execute a web search and return normalized results."""
    results = search_web_tavily(query=query, max_results=config.search.max_search_results)
    sources = []
    for r in results:
        sources.append(RawSourceData(
            source_id=str(uuid.uuid4()),
            source_name=r.get("title", "Unknown Source"),
            source_type=SourceType.WEB_API,
            url=r.get("url", ""),
            raw_content=r.get("content", ""),
            metadata={"score": r.get("score", 0.0), "query": query},
            retrieved_at=datetime.utcnow(),
            retrieval_status="success",
        ))
    return sources


def _execute_document_search(query: str) -> list[RawSourceData]:
    """Search document store for relevant content."""
    docs = load_documents(query=query)
    sources = []
    for doc in docs:
        sources.append(RawSourceData(
            source_id=str(uuid.uuid4()),
            source_name=doc.get("title", "Document"),
            source_type=SourceType.DOCUMENT,
            url=doc.get("source", None),
            raw_content=doc.get("content", ""),
            metadata=doc.get("metadata", {}),
            retrieved_at=datetime.utcnow(),
            retrieval_status="success",
        ))
    return sources


def _execute_data_parse(query: str) -> list[RawSourceData]:
    """Parse provided/structured data sources."""
    data_items = parse_provided_data(query=query)
    sources = []
    for item in data_items:
        sources.append(RawSourceData(
            source_id=str(uuid.uuid4()),
            source_name=item.get("name", "Provided Data"),
            source_type=SourceType.PROVIDED_DATA,
            raw_content=item.get("content", ""),
            metadata=item.get("metadata", {}),
            retrieved_at=datetime.utcnow(),
            retrieval_status="success",
        ))
    return sources


# Tool registry: name → function
_TOOL_REGISTRY = {
    "web_search": _execute_web_search,
    "document_search": _execute_document_search,
    "data_parse": _execute_data_parse,
}


def _llm_select_tools(query: SearchQuery, llm) -> list[dict]:
    """
    Use the LLM to decide which tools to invoke for this query.

    This is the core of LLM-driven tool selection: the model analyzes
    the query's intent and decides which retrieval tools will yield
    the best results, optionally rephrasing the query for each tool.

    Falls back to a heuristic dispatch if the LLM call fails.
    """
    messages = [
        SystemMessage(content=TOOL_SELECTOR_PROMPT),
        HumanMessage(content=(
            f"Query: {query.query_text}\n"
            f"Target source type hint: {query.target_source.value}\n"
            f"Priority: {query.priority}\n"
            f"Rationale: {query.rationale}"
        )),
    ]

    try:
        response = llm.invoke(messages)

        # Guardrail: check for refusal
        refusal = detect_refusal(response.content)
        if refusal.is_refusal:
            logger.warning("Tool selector LLM refused: %s", refusal.refusal_type)
            return _heuristic_fallback(query)

        # Guardrail: enforce output schema
        schema_result = enforce_json_schema(
            response.content,
            required_keys=["tool_decisions"],
        )
        if not schema_result.is_valid:
            logger.warning("Tool selector output invalid: %s", schema_result.errors)
            return _heuristic_fallback(query)

        decisions = schema_result.parsed_data.get("tool_decisions", [])

        # Validate tool names exist in registry
        valid_decisions = []
        for d in decisions:
            tool_name = d.get("tool_name", "")
            if tool_name in _TOOL_REGISTRY and d.get("expected_value") != "low":
                valid_decisions.append(d)
            else:
                logger.debug("Skipping unknown/low-value tool: %s", tool_name)

        if not valid_decisions:
            return _heuristic_fallback(query)

        logger.info(
            "LLM tool selection for '%s': %s",
            query.query_text[:50],
            [d["tool_name"] for d in valid_decisions],
        )
        return valid_decisions

    except Exception as e:
        logger.warning("LLM tool selection failed: %s — using heuristic fallback", e)
        return _heuristic_fallback(query)


def _heuristic_fallback(query: SearchQuery) -> list[dict]:
    """
    Deterministic fallback when LLM tool selection fails.

    Uses the Planner's target_source hint as a simple dispatch.
    This ensures the pipeline never stalls even without LLM access.
    """
    source_to_tool = {
        SourceType.WEB_API: "web_search",
        SourceType.DOCUMENT: "document_search",
        SourceType.PROVIDED_DATA: "data_parse",
        SourceType.DATABASE: "data_parse",
    }
    tool_name = source_to_tool.get(query.target_source, "web_search")
    return [{
        "tool_name": tool_name,
        "optimized_query": query.query_text,
        "reasoning": f"Heuristic fallback: target_source={query.target_source.value}",
        "priority": query.priority,
        "expected_value": "medium",
    }]


def gatherer_node(state: dict) -> dict:
    """
    Gatherer Agent node function for LangGraph.

    Workflow:
      1. Read search queries from state
      2. For each query, ask the LLM which tools to use (tool selection)
      3. Execute selected tools with optimized queries
      4. If a tool fails, the LLM can suggest an alternative (fallback)
      5. Collect all sources and write to state

    Args:
        state: Current ResearchState dictionary.

    Returns:
        State update with raw_sources and control fields.
    """
    queries = state.get("search_queries", [])
    corr_id = state.get("correlation_id", "?")[:12]
    logger.info("[%s] Gatherer Agent activated with %d queries", corr_id, len(queries))

    # Initialize tool-selection LLM (lightweight model for speed)
    tool_selector_llm = ChatOpenAI(
        model=config.llm.model_extraction,  # Use cheaper model for tool selection
        api_key=config.llm.api_key,
        temperature=0.1,
        response_format={"type": "json_object"},
    )

    all_sources: list[RawSourceData] = []
    errors: list[str] = []
    tool_selection_log: list[dict] = []

    # Sort queries by priority (1=highest)
    sorted_queries = sorted(queries, key=lambda q: q.priority)

    for query in sorted_queries:
        # ── Step 1: LLM decides which tools to use ─────────────────
        tool_decisions = _llm_select_tools(query, tool_selector_llm)

        # ── Step 2: Execute each selected tool ─────────────────────
        for decision in tool_decisions:
            tool_name = decision["tool_name"]
            optimized_query = decision.get("optimized_query", query.query_text)

            logger.info(
                "[%s] Tool '%s' selected for query: %s (reason: %s)",
                corr_id, tool_name, optimized_query[:60],
                decision.get("reasoning", "N/A")[:60],
            )

            # Track tool selection for traceability
            tool_selection_log.append({
                "query": query.query_text[:80],
                "tool": tool_name,
                "optimized_query": optimized_query[:80],
                "reasoning": decision.get("reasoning", ""),
            })

            try:
                tool_fn = _TOOL_REGISTRY[tool_name]
                sources = tool_fn(optimized_query)
                all_sources.extend(sources)
            except Exception as e:
                logger.error(
                    "[%s] Tool '%s' failed for '%s': %s",
                    corr_id, tool_name, optimized_query[:50], e,
                )
                all_sources.append(RawSourceData(
                    source_id=str(uuid.uuid4()),
                    source_name=f"Failed: {tool_name} — {optimized_query[:50]}",
                    source_type=SourceType.WEB_API,
                    raw_content="",
                    retrieval_status="failed",
                    error_message=str(e),
                ))
                errors.append(f"Tool '{tool_name}' failed: {str(e)}")

    # ── Summarize results ──────────────────────────────────────────
    successful = [s for s in all_sources if s.retrieval_status == "success"]
    failed = [s for s in all_sources if s.retrieval_status == "failed"]

    if failed:
        errors.extend(f"Failed: {s.source_name} — {s.error_message}" for s in failed)

    source_types = set(s.source_type.value for s in successful)
    logger.info(
        "[%s] Gatherer completed: %d successful, %d failed, types: %s, tools used: %s",
        corr_id, len(successful), len(failed), source_types,
        list({d["tool"] for d in tool_selection_log}),
    )

    return {
        "raw_sources": all_sources,
        "current_stage": "gathering_complete",
        "error_log": errors,
        "messages": [HumanMessage(
            content=f"[Gatherer] Retrieved {len(successful)} sources "
                    f"({len(failed)} failed) from types: {', '.join(source_types)}. "
                    f"Tools selected by LLM: {[d['tool'] for d in tool_selection_log]}"
        )],
        "status_transitions": [{
            "stage": "gatherer",
            "status": "tool_selection_complete",
            "tool_log": tool_selection_log,
        }],
    }
