"""
Gatherer Agent — Stage 2 of the Research Workflow.

═══════════════════════════════════════════════════════════════════
PURPOSE:
    Executes search queries generated by the Planner across multiple
    source types (web APIs, documents, provided data) and collects
    raw source material.

HOW IT WORKS (Step-by-Step):
    1. Reads search_queries from the state (produced by Planner).
    2. Groups queries by source type (web_api, document, provided_data).
    3. For each query, dispatches to the appropriate tool:
       - Web API queries → Tavily Search / Bing API
       - Document queries → PDF/document loader + vector search
       - Provided data → Parses user-supplied datasets
    4. Each retrieval is wrapped in try/except for fault tolerance.
    5. Results are normalized into RawSourceData objects.
    6. All raw sources are written to the shared state.

PARALLEL EXECUTION:
    In production, web queries can be dispatched in parallel using
    LangGraph's Send API or asyncio.gather() to reduce latency.
    This implementation uses sequential execution for clarity.

TRIGGER:
    Activated after the Planner completes successfully (via
    route_after_planning conditional edge).

ERROR HANDLING:
    - Individual source failures are logged but don't halt the pipeline.
    - Each RawSourceData includes a retrieval_status field.
    - If ALL sources fail, the router retries or triggers error_handler.
═══════════════════════════════════════════════════════════════════
"""

from __future__ import annotations
import uuid
import logging
from datetime import datetime
from langchain_core.messages import HumanMessage

from config import config
from models.source import RawSourceData, SourceType, SearchQuery
from tools.web_search import search_web_tavily
from tools.document_loader import load_documents
from tools.data_parser import parse_provided_data

logger = logging.getLogger(__name__)


def _gather_from_web(query: SearchQuery) -> list[RawSourceData]:
    """Execute a web search query and return raw source data."""
    try:
        results = search_web_tavily(
            query=query.query_text,
            max_results=config.search.max_search_results,
        )
        sources = []
        for r in results:
            sources.append(RawSourceData(
                source_id=str(uuid.uuid4()),
                source_name=r.get("title", "Unknown Source"),
                source_type=SourceType.WEB_API,
                url=r.get("url", ""),
                raw_content=r.get("content", ""),
                metadata={"score": r.get("score", 0.0), "query": query.query_text},
                retrieved_at=datetime.utcnow(),
                retrieval_status="success",
            ))
        return sources
    except Exception as e:
        logger.error("Web search failed for query '%s': %s", query.query_text, e)
        return [RawSourceData(
            source_id=str(uuid.uuid4()),
            source_name=f"Failed: {query.query_text[:50]}",
            source_type=SourceType.WEB_API,
            raw_content="",
            retrieval_status="failed",
            error_message=str(e),
        )]


def _gather_from_documents(query: SearchQuery) -> list[RawSourceData]:
    """Search document store for relevant content."""
    try:
        docs = load_documents(query=query.query_text)
        sources = []
        for doc in docs:
            sources.append(RawSourceData(
                source_id=str(uuid.uuid4()),
                source_name=doc.get("title", "Document"),
                source_type=SourceType.DOCUMENT,
                url=doc.get("source", None),
                raw_content=doc.get("content", ""),
                metadata=doc.get("metadata", {}),
                retrieved_at=datetime.utcnow(),
                retrieval_status="success",
            ))
        return sources
    except Exception as e:
        logger.error("Document search failed for query '%s': %s", query.query_text, e)
        return [RawSourceData(
            source_id=str(uuid.uuid4()),
            source_name=f"Doc search failed: {query.query_text[:50]}",
            source_type=SourceType.DOCUMENT,
            raw_content="",
            retrieval_status="failed",
            error_message=str(e),
        )]


def _gather_from_data(query: SearchQuery) -> list[RawSourceData]:
    """Parse provided/structured data sources."""
    try:
        data_items = parse_provided_data(query=query.query_text)
        sources = []
        for item in data_items:
            sources.append(RawSourceData(
                source_id=str(uuid.uuid4()),
                source_name=item.get("name", "Provided Data"),
                source_type=SourceType.PROVIDED_DATA,
                raw_content=item.get("content", ""),
                metadata=item.get("metadata", {}),
                retrieved_at=datetime.utcnow(),
                retrieval_status="success",
            ))
        return sources
    except Exception as e:
        logger.error("Data parsing failed for query '%s': %s", query.query_text, e)
        return []


# ── Dispatch table: source type → gathering function ──────────────
_GATHER_DISPATCH = {
    SourceType.WEB_API: _gather_from_web,
    SourceType.DOCUMENT: _gather_from_documents,
    SourceType.PROVIDED_DATA: _gather_from_data,
    SourceType.DATABASE: _gather_from_data,  # Fallback
}


def gatherer_node(state: dict) -> dict:
    """
    Gatherer Agent node function for LangGraph.

    Args:
        state: Current ResearchState dictionary.

    Returns:
        State update with raw_sources and control fields.
    """
    queries = state.get("search_queries", [])
    logger.info("Gatherer Agent activated with %d queries", len(queries))

    all_sources: list[RawSourceData] = []
    errors: list[str] = []

    # ── Sort queries by priority (1=highest) ───────────────────────
    sorted_queries = sorted(queries, key=lambda q: q.priority)

    for query in sorted_queries:
        logger.info(
            "Gathering [%s] priority=%d: %s",
            query.target_source.value, query.priority, query.query_text[:80]
        )

        gather_fn = _GATHER_DISPATCH.get(query.target_source, _gather_from_web)
        sources = gather_fn(query)
        all_sources.extend(sources)

    # ── Summarize results ──────────────────────────────────────────
    successful = [s for s in all_sources if s.retrieval_status == "success"]
    failed = [s for s in all_sources if s.retrieval_status == "failed"]

    if failed:
        errors = [f"Failed to retrieve: {s.source_name} — {s.error_message}" for s in failed]

    source_types = set(s.source_type.value for s in successful)
    logger.info(
        "Gatherer completed: %d successful, %d failed, source types: %s",
        len(successful), len(failed), source_types
    )

    return {
        "raw_sources": all_sources,
        "current_stage": "gathering_complete",
        "error_log": errors,
        "messages": [HumanMessage(
            content=f"[Gatherer] Retrieved {len(successful)} sources "
                    f"({len(failed)} failed) from types: {', '.join(source_types)}"
        )],
    }
