"""
Pydantic models for source data, citations, and extracted facts.
These models are used throughout the pipeline for type safety and validation.
"""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


class SourceType(str, Enum):
    """Classification of information source types."""
    WEB_API = "web_api"
    DOCUMENT = "document"
    PROVIDED_DATA = "provided_data"
    DATABASE = "database"


class Citation(BaseModel):
    """A trackable citation linking a claim to its source."""
    source_id: str = Field(..., description="Unique identifier for the source")
    source_name: str = Field(..., description="Human-readable source name")
    source_type: SourceType = Field(..., description="Type of source")
    url: Optional[str] = Field(None, description="URL if available")
    retrieved_at: datetime = Field(default_factory=datetime.utcnow)
    snippet: str = Field("", description="Relevant text snippet from the source")
    page_or_section: Optional[str] = Field(None, description="Page number or section reference")


class ExtractedFact(BaseModel):
    """A single fact or claim extracted from a source."""
    fact_id: str = Field(..., description="Unique identifier for this fact")
    claim: str = Field(..., description="The factual claim or data point")
    category: str = Field(..., description="Topic category this fact belongs to")
    confidence: float = Field(
        0.0, ge=0.0, le=1.0,
        description="Confidence score (0.0-1.0) of extraction accuracy"
    )
    citations: list[Citation] = Field(default_factory=list)
    is_quantitative: bool = Field(False, description="Whether this is a numeric/statistical claim")
    raw_value: Optional[str] = Field(None, description="Raw numeric value if quantitative")


class SourceAgreement(str, Enum):
    """Classification of how sources relate on a point."""
    AGREE = "agree"
    CONFLICT = "conflict"
    PARTIAL = "partial"
    UNIQUE = "unique"  # Only one source mentions this


class ComparisonResult(BaseModel):
    """Result of comparing facts across sources."""
    topic: str = Field(..., description="The topic or claim being compared")
    agreement_status: SourceAgreement = Field(..., description="How sources relate")
    supporting_facts: list[ExtractedFact] = Field(default_factory=list)
    conflicting_facts: list[ExtractedFact] = Field(default_factory=list)
    explanation: str = Field("", description="Explanation of agreement/conflict")
    confidence: float = Field(0.0, ge=0.0, le=1.0)


class SearchQuery(BaseModel):
    """A structured search query generated by the planner."""
    query_text: str = Field(..., description="The search query string")
    target_source: SourceType = Field(SourceType.WEB_API, description="Preferred source type")
    priority: int = Field(1, ge=1, le=5, description="Priority level (1=highest)")
    rationale: str = Field("", description="Why this query is needed")


class RawSourceData(BaseModel):
    """Raw data retrieved from a single source before extraction."""
    source_id: str
    source_name: str
    source_type: SourceType
    url: Optional[str] = None
    raw_content: str = ""
    metadata: dict = Field(default_factory=dict)
    retrieved_at: datetime = Field(default_factory=datetime.utcnow)
    retrieval_status: str = "success"  # success | partial | failed
    error_message: Optional[str] = None
